version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-latest
  jobs:
    post_build:
      - export PROJ_LIB="$CONDA_PREFIX/share/proj"

conda:
  environment: environment.yml

sphinx:
  builder: html
  configuration: conf.py
